namespace ZuraTDD;

/// <summary>
/// A marker interface for services classes autogenerated for each test case class.
/// </summary>
public interface ITestSubjectDependencies
{
	/// <summary>
	/// An indexer returning a fake service by its name.
	/// </summary>
	object this[string dependencyName] { get; }
}
