using System;

namespace ZuraTDD;

/// <summary>
/// Marks a method or property as a source of <see cref="ITestPart" />-s for a test method
/// to be generated by the ZuraTDD source generator.
/// Must be used inside a class decorated with <see cref="ZuraTestClass{TSubject}"/>.
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = false)]
public class ZuraTest : Attribute
{
	/// <summary>
	/// Name of the test displayed in the test explorer.
	/// </summary>
	public string Name { get; }

	/// <param name="name">Name of the test displayed in the test explorer.</param>
	public ZuraTest(string name)
	{
		this.Name = name;
	}
}
