using System;

namespace ZuraTDD;

/// <summary>
/// Marks a method or property as a source of <see cref="ITestPart" />-s for a test method
/// to be generated by the ZuraTDD source generator.
/// </summary>
/// <typeparam name="T"></typeparam>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = false)]
public class ZuraTest<T>
	: Attribute
	where T : TestCase
{
	/// <summary>
	/// Name of the test displayed in the test explorer.
	/// </summary>
	public string Name { get; }

	/// <summary>
	/// Generates a test method using the specified <see cref="ITestCase{TSubject}" /> type and the
	/// <see cref="ITestPart" />-s returned by the decorated method or property.
	/// </summary>
	/// <param name="name">Name of the test displayed in the test explorer.</param>
	public ZuraTest(string name)
	{
		this.Name = name;
	}
}
