using System;
using ZuraTDD.TestGenerator.DataModel;

namespace ZuraTDD.TestGenerator;

internal class TestTemplateProcessor
{
	public static string TestMethod(TestSpecification testSpecification)
	{
		return testSpecification.TestFramework switch
		{
			TestFramework.MsTest => TestCode_MsTest(testSpecification),
			TestFramework.XUnit => TestCode_XUnit(testSpecification),

			_ => throw new System.NotImplementedException(),
		};
	}

	private static string TestCode_XUnit(TestSpecification testSpecification)
	{
		string invocationBrackets = testSpecification.IsSourceMethod ? "()" : string.Empty;

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using System;
			using System.Threading.Tasks;
			using Xunit;
			using ZuraTDD;

			namespace {{testSpecification.OutputNamespace}};

			public partial class {{testSpecification.OutputTypeName}}
			{
				[Fact(DisplayName = "{{testSpecification.TestName}}")]
				public async Task {{testSpecification.TestPartSourceName}}_Runner()
				{
					var testCase = new {{testSpecification.TestCaseClassName}} (
						name: "{{testSpecification.TestName}}",
						testParts: {{testSpecification.TestPartSourceName}}{{invocationBrackets}});

					await testCase.RunTestAsync();
				}
			}
			""";
	}

	private static string TestCode_MsTest(TestSpecification testSpecification)
	{
		string invocationBrackets = testSpecification.IsSourceMethod ? "()" : string.Empty;

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using System;
			using System.Threading.Tasks;
			using Microsoft.VisualStudio.TestTools.UnitTesting;
			using ZuraTDD;

			namespace {{testSpecification.OutputNamespace}};

			public partial class {{testSpecification.OutputTypeName}}
			{
				[TestMethod(DisplayName = "{{testSpecification.TestName}}")]
				public async Task {{testSpecification.TestPartSourceName}}_Runner()
				{
					var testCase = new {{testSpecification.TestCaseClassName}} (
						name: "{{testSpecification.TestName}}",
						testParts: {{testSpecification.TestPartSourceName}}{{invocationBrackets}});

					await testCase.RunTestAsync();
				}
			}
			""";
	}
}
