using ZuraTDD.TestGenerator.DataModel;

namespace ZuraTDD.TestGenerator;

internal class TestTemplateProcessor
{
	public static string TestMethod(TestSpecification testSpecification)
	{
		string invocationBrackets = testSpecification.IsSourceMethod ? "()" : string.Empty;

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using System;
			using System.Threading.Tasks;
			using Microsoft.VisualStudio.TestTools.UnitTesting;
			using ZuraTDD;

			namespace {{testSpecification.OutputNamespace}};

			public partial class {{testSpecification.OutputTypeName}}
			{
				[TestMethod(DisplayName = "{{testSpecification.TestName}}")]
				public async Task {{testSpecification.TestPartSourceName}}_Runner()
				{
					var testCase = new {{testSpecification.TestCaseClassName}} (
						name: "{{testSpecification.TestName}}",
						testParts: {{testSpecification.TestPartSourceName}}{{invocationBrackets}});

					await testCase.RunTestAsync();
				}
			}
			""";
	}
}
