// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using ExampleProject.Model;
using ZuraTDD;
using ZuraTDD.Tests.Example;

namespace ZuraTDD.Tests.Example;

/// <summary>
/// Implementation of the test case for <see cref="ExampleProject.ContentPublishedEventHandler" />.
/// Import this class with "using static ExampleProject.Tests.ContentPublishedEventHandlerTestCase;"
/// in order to simplify access to "Receives", "When" and "Expect" static classes.
/// </summary>
internal partial class ContentPublishedEventHandlerTestCase
	: TestCase<global::ExampleProject.ContentPublishedEventHandler, ContentPublishedEventHandlerServices>
{
	public ContentPublishedEventHandlerTestCase(
		string name,
		params ITestPart[] testParts)
		: base(name, testParts)
	{
	}

	/// <summary>
	/// Gets an instance of the class being tested.
	/// </summary>
	public override global::ExampleProject.ContentPublishedEventHandler
		GetTestSubject(IEnumerable<INamedDependencySetup> dependencySetups)
	{
		return new global::ExampleProject.ContentPublishedEventHandler(
			this.Dependencies.CustomerRepository,
			this.Dependencies.EmailSender);
	}

	protected override ContentPublishedEventHandlerServices
		BuildTestSubjectDependencies(IEnumerable<INamedDependencySetup> dependencySetups)
	{
		return new(dependencySetups);
	}

	/// <summary>
	/// A static class creating method calls for the tested object.
	/// </summary>
	internal static class Receives
	{
		/// <summary>
		/// Defines a call to the <see cref="global::ExampleProject.ContentPublishedEventHandler.HandleContentPublish"/> method.
		/// </summary>
		public static TestedTaskCall
			HandleContentPublish(Content? content = default)
		{
#pragma warning disable CS8604
			return new(
				obj => (obj as ExampleProject.ContentPublishedEventHandler)!.HandleContentPublish(content));
#pragma warning restore CS8604
		}
	}

	/// <summary>
	/// A static class creating behaviors for the tested object's dependencies.
	/// </summary>
	internal static class When
	{
		/// <summary>
		/// A builder producing behaviors for <see cref="ExampleProject.ICustomerRepository" />
		/// which will be passed as "CustomerRepository" to the test subject.
		/// </summary>
		internal static ICustomerRepository_NamedInstanceBuilder CustomerRepository
			=> new ICustomerRepository_NamedInstanceBuilder("CustomerRepository");

		/// <summary>
		/// A builder producing behaviors for <see cref="ExampleProject.IEmailSender" />
		/// which will be passed as "EmailSender" to the test subject.
		/// </summary>
		internal static IEmailSender_NamedInstanceBuilder EmailSender
			=> new IEmailSender_NamedInstanceBuilder("EmailSender");
	}

	/// <summary>
	/// A static class creating expectations which must be satisfied after the tested method completes.
	/// </summary>
	internal static class Expect
	{
		public static ITestResultExpectation ExceptionToBeThrown<TException>()
			where TException : Exception
		{
			return new ExpectedException<TException>();
		}

		public static ITestResultExpectation ResultMatching<TResult>(Predicate<TResult> predicate)
		{
			return new ExpectedResultMatching<TResult>(predicate);
		}

		public static ITestResultExpectation ResultEqualTo<TResult>(TResult expectedValue)
		{
			return new ExpectedResultMatching<TResult>(value => value!.Equals(expectedValue));
		}

		/// <summary>
		/// A builder producing expectations for <see cref="ExampleProject.ICustomerRepository" />
		/// which will be passed as "CustomerRepository" to the test subject.
		/// </summary>
		internal static ICustomerRepository_ExpectStaticBuilder CustomerRepository
			=> new ICustomerRepository_ExpectStaticBuilder("CustomerRepository");

		/// <summary>
		/// A builder producing expectations for <see cref="ExampleProject.IEmailSender" />
		/// which will be passed as "EmailSender" to the test subject.
		/// </summary>
		internal static IEmailSender_ExpectStaticBuilder EmailSender
			=> new IEmailSender_ExpectStaticBuilder("EmailSender");
	}
}
