// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using ZuraTDD;
using ZuraTDD.Tests.Example;

namespace ZuraTDD.Tests.Example;

/// <summary>
/// Services used by the test cases for <see cref="global::ExampleProject.ContentPublishedEventHandler" />.
/// </summary>
internal class ContentPublishedEventHandlerServices : ITestSubjectServices
{
	private DependencyCollection fakeServices;

	private readonly INamedDependencySetup[] dependencySetup;

	public ContentPublishedEventHandlerServices(IEnumerable<INamedDependencySetup> dependencySetup)
	{
		this.dependencySetup = dependencySetup.ToArray();
		this.fakeServices = new(
			KeyValuePair.Create<string, Func<FakeService>>(
				"CustomerRepository",
				() => new ICustomerRepository_Fake(dependencySetup.OnlyBehaviorsWithName("CustomerRepository"))),
			KeyValuePair.Create<string, Func<FakeService>>(
				"EmailSender",
				() => new IEmailSender_Fake(dependencySetup.OnlyBehaviorsWithName("EmailSender"))));
	}

	/// <summary>
	/// Mock for the "CustomerRepository" parameter of the test subject constructor.
	/// Returns an instance of <see cref="ExampleProject.ICustomerRepository" />.
	/// </summary>
	public ExampleProject.ICustomerRepository CustomerRepository
		=> (ExampleProject.ICustomerRepository)fakeServices["CustomerRepository"];

	/// <summary>
	/// Mock for the "EmailSender" parameter of the test subject constructor.
	/// Returns an instance of <see cref="ExampleProject.IEmailSender" />.
	/// </summary>
	public ExampleProject.IEmailSender EmailSender
		=> (ExampleProject.IEmailSender)fakeServices["EmailSender"];

	public FakeService this[string name] => fakeServices[name];
}
