using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	/// <summary>
	/// Generates code for the static class containing MethodInfo tokens for all public methods of the service.
	/// </summary>
	public static string MockedTypeBuilderClassesCode(MockedTypeSpecification mockedType)
	{
		var methods = string.Join(
			"\n\n",
			mockedType.Methods.Select(m => Functions.MockedMethodBuilderDeclaration(mockedType, m)));

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;
			using ZuraTDD.BuildingBlocks;
			
			namespace {{mockedType.OutputNamespace}};

			/// <summary>
			/// Instance builder of <see cref="{{mockedType.TypeInfo.FullyQualifiedTypeName}}" />.
			/// </summary>
			internal class {{mockedType.BuilderTypeName}}
				: {{mockedType.TypeInfo.TypeName}}_BehaviorBuilder
				, IBuild<{{mockedType.MockedFakeTypeName}}>
			{
				public {{mockedType.BuilderTypeName}}()
					: base(new BehaviorSetupCollector())
				{
				}

				public {{mockedType.MockedFakeTypeName}} BuildInstance()
				{
					var collector = base.behaviorSetupProcessor as BehaviorSetupCollector;

					return new(
						collector!
							.BuildSetupCollection()
							.OfType<BehaviorSetup>());
				}
			}

			/// <summary>
			/// Abstract builder of <see cref="{{mockedType.TypeInfo.FullyQualifiedTypeName}}" />.
			/// </summary>
			internal abstract class {{mockedType.TypeInfo.TypeName}}_BehaviorBuilder
				: MockedObjectBuilder
			{
				public {{mockedType.TypeInfo.TypeName}}_BehaviorBuilder(
					IBehaviorSetupProcessor behaviorSetupProcessor)
					: base(behaviorSetupProcessor)
				{
				}

			{{methods}}
			}
			""";
	}

	public static string DependencyStaticBuilderCode(
		DependencySpecification dependency)
	{
		return dependency.IsMockable
			? AbstractDependencyStaticBuilderCode(dependency)
			: NonAbstractDependencyStaticBuilderCode(dependency);
	}

	private static string AbstractDependencyStaticBuilderCode(
		DependencySpecification dependency)
	{
		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;

			namespace {{dependency.OutputNamespace}};

			internal class {{dependency.DependencyType.TypeName}}_NamedInstanceBuilder : {{dependency.DependencyType.TypeName}}_BehaviorBuilder
			{
				private readonly string dependencyName;

				public {{dependency.DependencyType.TypeName}}_NamedInstanceBuilder(string dependencyName)
					: base(new BehaviorSetupOwnerName(dependencyName))
				{
					this.dependencyName = dependencyName;
				}

				/// <summary>
				/// Returns an ITestPart which will make the TestSubject receive the specified instance as its dependency.
				/// </summary>
				/// <param name="instance">Instance of {{dependency.DependencyType.TypeName}} used as dependency.</param>
				public NamedDependency<{{dependency.DependencyType.FullyQualifiedTypeName}}> Is(
					{{dependency.DependencyType.FullyQualifiedTypeName}} instance)
				{
					return new (
						instance,
						this.dependencyName);
				}
			}
			""";
	}

	private static string NonAbstractDependencyStaticBuilderCode(
		DependencySpecification dependency)
	{
		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;

			namespace {{dependency.OutputNamespace}};

			/// <summary>
			/// A builder of a class which is not possible to mock. It only exposes the "Is" method.
			/// </summary>
			internal class {{dependency.DependencyType.TypeName}}_NamedInstanceBuilder
			{
				private readonly string dependencyName;

				public {{dependency.DependencyType.TypeName}}_NamedInstanceBuilder(string dependencyName)
				{
					this.dependencyName = dependencyName;
				}

				/// <summary>
				/// Returns an ITestPart which will make the TestSubject receive the specified instance as its dependency.
				/// </summary>
				/// <param name="instance">Instance of {{dependency.DependencyType.TypeName}} used as dependency.</param>
				public NamedDependency<{{dependency.DependencyType.FullyQualifiedTypeName}}> Is(
					{{dependency.DependencyType.FullyQualifiedTypeName}} instance)
				{
					return new (
						instance,
						this.dependencyName);
				}
			}
			""";
	}
}

static file class Functions
{
	public static string MockedMethodBuilderDeclaration(
		MockedTypeSpecification mockedType,
		MethodSpecification method)
	{
		var paramsString = string.Join(",\n\t\t\t\t", method.Parameters.Select(p => $"{p.Name} ?? new ValueConstraint<{p.Type}>()"));
		var genericParameters = method.GetMethodGenericTypeParametersString();
		var valueSetConstraint = method.Parameters.Any()
			? $"""

						new ValueSetConstraint([
							{paramsString}
						]),
			"""
			: "";

		return
			$$"""
				/// <summary>
				/// Creates behavior builder for <see cref="{{mockedType.TypeInfo.TypeName}}.{{method.MethodName}}" />.
				/// </summary>
				public {{PrepareCallSpecificationType(method)}}
					{{method.MethodName}}{{genericParameters}}({{PrepareParameterList(method)}})
				{
					return new(
						{{mockedType.MockedTypeMethodsTypeName}}.{{method.MethodCodeName}},{{valueSetConstraint}}
						new GenericTypeParameterSetConstraint([{{GetGenericTypeParameterValuesString(method)}}]),
						this.behaviorSetupProcessor);
				}
			""";
	}

	private static string PrepareCallSpecificationType(MethodSpecification methodSpecification)
	{
		return methodSpecification.MethodType switch
		{
			MethodType.Void => $"ActionBehaviorBuilder{methodSpecification.GetGenericParamsString()}",
			MethodType.TaskOfT => $"FuncTaskOfBehaviorBuilder{methodSpecification.GetAsyncMethodGenericParamsString()}",
			MethodType.ValueTaskOfT => $"FuncValueTaskOfBehaviorBuilder{methodSpecification.GetAsyncMethodGenericParamsString()}",
			_ => $"FuncBehaviorBuilder{methodSpecification.GetGenericParamsString()}",
		};
	}

	private static string PrepareParameterList(MethodSpecification method)
	{
		if (method.Parameters.Count == 0)
			return "";

		var parameterDeclarations = method.Parameters
			.Select(p => $"ValueConstraint<{p.Type}>? {p.Name} = null");

		return "\n\t\t" + string.Join(",\n\t\t", parameterDeclarations);
	}

	private static string GetGenericTypeParameterValuesString(MethodSpecification method)
	{
		if (method.GenericTypeParameters.Count == 0)
			return "";

		var genericParameterValues = method.GenericTypeParameters
			.Select(p => $"new GenericTypeParameterConstraint(typeof({p.Name}))");

		return "\n\t\t\t\t" + string.Join(",\n\t\t\t\t", genericParameterValues);
	}
}
