using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	/// <summary>
	/// Generates code for the static class containing MethodInfo tokens for all public methods of the service.
	/// </summary>
	public static string ServiceBuilderClassesCode(DependencySpecification service)
	{
		var methods = string.Join(
			"\n\n",
			service.Methods.Select(m => Functions.ServiceBuilderMethodCode(service, m)));

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;

			namespace {{service.OutputNamespace}};

			/// <summary>
			/// Instance builder of <see cref="{{service.FullyQualifiedName}}" />.
			/// </summary>
			internal class {{service.BuilderTypeName}}
				: {{service.ServiceTypeName}}_BehaviorBuilder
				, IBuild<{{service.ServiceFakeTypeName}}>
			{
				public {{service.BuilderTypeName}}()
					: base(new BehaviorSetupCollector())
				{
				}

				public {{service.ServiceFakeTypeName}} BuildInstance()
				{
					var collector = base.behaviorSetupProcessor as BehaviorSetupCollector;

					return new(
						collector!
							.BuildSetupCollection()
							.OfType<BehaviorSetup>());
				}
			}

			/// <summary>
			/// Abstract builder of <see cref="{{service.FullyQualifiedName}}" />.
			/// </summary>
			internal abstract class {{service.ServiceTypeName}}_BehaviorBuilder
				: FakeServiceBuilder
			{
				public {{service.ServiceTypeName}}_BehaviorBuilder(
					IBehaviorSetupProcessor behaviorSetupProcessor)
					: base(behaviorSetupProcessor)
				{
				}

			{{methods}}
			}
			""";
	}

	public static string ServiceStaticBuilderCode(
		DependencySpecification service)
	{
		// TODO should this logic be kept here or in the invoking class?
		if (service.IsInterface)
			return ServiceStaticAbstractBuilderCode(service);
		else
			return ServiceStaticIsOnlyBuilderCode(service);
	}

	private static string ServiceStaticAbstractBuilderCode(
		DependencySpecification service)
	{
		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;

			namespace {{service.OutputNamespace}};

			internal class {{service.ServiceTypeName}}_NamedInstanceBuilder : {{service.ServiceTypeName}}_BehaviorBuilder
			{
				private readonly string serviceName;

				public {{service.ServiceTypeName}}_NamedInstanceBuilder(string serviceName)
					: base(new BehaviorSetupOwnerName(serviceName))
				{
					this.serviceName = serviceName;
				}

				/// <summary>
				/// Returns an ITestPart which will make the TestSubject receive the specified instance as its dependency.
				/// </summary>
				/// <param name="instance">Instance of {{service.ServiceTypeName}} used as dependency.</param>
				public NamedDependency<{{service.FullyQualifiedName}}> Is(
					{{service.FullyQualifiedName}} instance)
				{
					return new (
						instance,
						this.serviceName);
				}
			}
			""";
	}

	private static string ServiceStaticIsOnlyBuilderCode(
		DependencySpecification service)
	{
		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;

			namespace {{service.OutputNamespace}};

			/// <summary>
			/// A builder of a class which is not possible to mock. It only exposes the "Is" method.
			/// </summary>
			internal class {{service.ServiceTypeName}}_NamedInstanceBuilder
			{
				private readonly string serviceName;

				public {{service.ServiceTypeName}}_NamedInstanceBuilder(string serviceName)
				{
					this.serviceName = serviceName;
				}

				/// <summary>
				/// Returns an ITestPart which will make the TestSubject receive the specified instance as its dependency.
				/// </summary>
				/// <param name="instance">Instance of {{service.ServiceTypeName}} used as dependency.</param>
				public NamedDependency<{{service.FullyQualifiedName}}> Is(
					{{service.FullyQualifiedName}} instance)
				{
					return new (
						instance,
						this.serviceName);
				}
			}
			""";
	}
}

static file class Functions
{
	public static string ServiceBuilderMethodCode(
		DependencySpecification service,
		MethodSpecification method)
	{
		var paramsString = string.Join(",\n\t\t\t\t", method.Parameters.Select(p => $"{p.Name} ?? new ValueConstraint<{p.Type}>()"));
		var valueSetConstraint = method.Parameters.Any()
			? $"""

						new ValueSetConstraint([
							{string.Join(",\n\t\t\t\t", method.Parameters.Select(p => $"{p.Name} ?? new ValueConstraint<{p.Type}>()"))}
						]),
			"""
			: "";

		return
			$$"""
				/// <summary>
				/// Creates behavior builder for <see cref="{{service.ServiceTypeName}}.{{method.MethodName}}" />.
				/// </summary>
				public {{PrepareCallSpecificationType(method)}}
					{{method.MethodName}}({{PrepareParameterList(method)}})
				{
					return new(
						{{service.ServiceMethodsTypeName}}.{{method.Token}},{{valueSetConstraint}}
						this.behaviorSetupProcessor);
				}
			""";
	}

	private static string PrepareCallSpecificationType(MethodSpecification methodSpecification)
	{
		return methodSpecification.MethodType switch
		{
			MethodType.Void => $"ActionBehaviorBuilder{methodSpecification.GetGenericParamsString()}",
			MethodType.TaskOfT => $"FuncTaskOfBehaviorBuilder{methodSpecification.GetAsyncMethodGenericParamsString()}",
			MethodType.ValueTaskOfT => $"FuncValueTaskOfBehaviorBuilder{methodSpecification.GetAsyncMethodGenericParamsString()}",
			_ => $"FuncBehaviorBuilder{methodSpecification.GetGenericParamsString()}",
		};
	}

	private static string PrepareParameterList(MethodSpecification method)
	{
		if (method.Parameters.Count == 0)
			return "";

		var parameterDeclarations = method.Parameters
			.Select(p => $"ValueConstraint<{p.Type}>? {p.Name} = null");

		return "\n\t\t" + string.Join(",\n\t\t", parameterDeclarations);
	}
}
