using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	public static string PrepareServicesClassCode(ServicesClassSpecification spec)
	{
		var serviceDeclarations = spec.Services.Select(s =>
			$$"""
				/// <summary>
				/// Substitute for <see cref="{{s.DeclaringNamespace}}.{{s.ServiceTypeName}}" />.
				/// </summary>
				public {{s.DeclaringNamespace}}.{{s.ServiceTypeName}} {{s.ServicePropertyName}}
					=> ({{s.DeclaringNamespace}}.{{s.ServiceTypeName}})fakeServices["{{s.ServicePropertyName}}"];
			""");

		var strServiceDeclarations = string.Join("\n\n", serviceDeclarations);

		var serviceCreation = spec.Services.Select(s =>
			$$"""
						KeyValuePair.Create("{{s.ServicePropertyName}}", new {{s.ServiceFakeTypeName}}() as FakeService)
			""");

		var strFakeServiceseParams = spec.Services.Any()
			? "\n" + string.Join(",\n", serviceCreation)
			: "";

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using System;
			using System.Collections.Generic;
			using ZuraTDD;

			namespace {{spec.OutputNamespace}};

			/// <summary>
			/// Services used by the test cases for <see cref="{{spec.TestSubjectClassName}}" />.
			/// </summary>
			internal class {{spec.ServicesClassName}} : ITestSubjectServices
			{
				private FakeServices fakeServices;

				public {{spec.ServicesClassName}}()
				{
					fakeServices = new({{strFakeServiceseParams}});
				}

				public FakeService this[string name] => fakeServices[name];

			{{strServiceDeclarations}}
			}
			""";
	}
}
