using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	public static string GenerateFakeServiceCode(ServiceSpecification service)
	{
		var methods = service.Methods
			.Select(m => Functions.GenerateFakeMethod(service, m));

		var methodsCode = string.Join("\n\n", methods);

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;
			
			namespace {{service.OutputNamespace}};

			/// <summary>
			/// A mock implementation of <see cref="{{service.FullyQualifiedName}}" />.
			/// </summary>
			internal class {{service.ServiceFakeTypeName}}
				: FakeService
				, {{service.FullyQualifiedName}}
			{
				public {{service.ServiceFakeTypeName}}(
					params IEnumerable<BehaviorSetup> behaviors)
					: base(behaviors)
				{
				}

				public {{service.ExpectTypeName}} GetExpectObject()
				{
					return new(this);
				}

			{{methodsCode}}
			}
			""";
	}
}

static file class Functions
{
	public static string GenerateFakeMethod(
		ServiceSpecification service,
		MethodSpecification method)
	{
		var paramValues = method.GetParamValuesString();
		var @return = method.ReturnType == "void" ? "" : "return ";
		var defaultResult = method.GetDefaultResult();
		defaultResult = defaultResult == ""
			? ""
			: $",\n\t\t\t{defaultResult}";

		return
			$$"""
				/// <summary>
				/// Simulates behavior for <see cref="{{service.ServiceTypeName}}.{{method.MethodName}}" />.
				/// </summary>
				public {{method.ReturnType}} {{method.MethodName}}({{ParameterDeclarations(method)}})
				{
					this.CallTracker.ReceiveCall(
						{{service.ServiceMethodsTypeName}}.{{method.Token}},
						[{{paramValues}}]);

					{{@return}}base.BehaviorSetupRunner.{{InvokeMethod(method)}}(
						{{service.ServiceMethodsTypeName}}.{{method.Token}}{{paramValues.PrependNotEmpty(",\n\t\t\t")}}{{defaultResult}});
				}
			""";
	}

	private static string ParameterDeclarations(MethodSpecification method)
	{
		if (method.Parameters.Count == 0)
			return "";

		var declarations = method.Parameters
			.Select(p => $"{p.Type} {p.Name}");

		return "\n\t\t" + string.Join(",\n\t\t", declarations);
	}

	private static string InvokeMethod(MethodSpecification method)
	{
		return method.ReturnType == "void"
			? $"InvokeActionBehavior{method.GetGenericParamsString()}"
			: $"InvokeFuncBehavior{method.GetGenericParamsString()}";
	}
}
