using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	/// <summary>
	/// Generates code for the static class containing MethodInfo tokens for all public methods of the service.
	/// </summary>
	public static string ServiceBuilderClassesCode(ServiceSpecification service)
	{
		var methods = string.Join(
			"\n\n",
			service.Methods.Select(m => Functions.ServiceBuilderMethodCode(service, m)));

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;

			namespace {{service.OutputNamespace}};

			/// <summary>
			/// Instance builder of <see cref="{{service.FullyQualifiedName}}" />.
			/// </summary>
			internal class {{service.BuilderTypeName}}
				: {{service.ServiceTypeName}}_BehaviorBuilder
				, IBuild<{{service.ServiceFakeTypeName}}>
			{
				public {{service.BuilderTypeName}}()
					: base(new BehaviorSetupCollector())
				{
				}

				public {{service.ServiceFakeTypeName}} BuildInstance()
				{
					var collector = base.behaviorSetupProcessor as BehaviorSetupCollector;

					return new(
						collector!.BuildSetupCollection());
				}
			}

			/// <summary>
			/// Abstract builder of <see cref="{{service.FullyQualifiedName}}" />.
			/// </summary>
			internal abstract class {{service.ServiceTypeName}}_BehaviorBuilder
				: FakeServiceBuilder
			{
				public {{service.ServiceTypeName}}_BehaviorBuilder(
					IBehaviorSetupProcessor behaviorSetupProcessor)
					: base(behaviorSetupProcessor)
				{
				}

			{{methods}}
			}
			""";
	}

	public static string ServiceStaticBuilderCode(
		ServiceSpecification service)
	{
		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;

			namespace {{service.OutputNamespace}};

			internal class {{service.ServiceTypeName}}_StaticBuilder : {{service.ServiceTypeName}}_BehaviorBuilder
			{
				public {{service.ServiceTypeName}}_StaticBuilder(string serviceName)
					: base(new BehaviorSetupOwnerName(serviceName))
				{
				}
			}
			""";
	}
}

static file class Functions
{
	public static string ServiceBuilderMethodCode(
		ServiceSpecification service,
		MethodSpecification method)
	{
		var paramsString = string.Join(",\n\t\t\t\t", method.Parameters.Select(p => $"{p.Name} ?? new ValueConstraint<{p.Type}>()"));
		var valueSetConstraint = method.Parameters.Any()
			? $"""

						new ValueSetConstraint([
							{string.Join(",\n\t\t\t\t", method.Parameters.Select(p => $"{p.Name} ?? new ValueConstraint<{p.Type}>()"))}
						]),
			"""
			: "";

		return
			$$"""
				/// <summary>
				/// Creates behavior builder for <see cref="{{service.ServiceTypeName}}.{{method.MethodName}}" />.
				/// </summary>
				public {{PrepareCallSpecificationType(method)}}
					{{method.MethodName}}({{PrepareParameterList(method)}})
				{
					return new(
						{{service.ServiceMethodsTypeName}}.{{method.Token}},{{valueSetConstraint}}
						this.behaviorSetupProcessor);
				}
			""";
	}

	private static string PrepareCallSpecificationType(MethodSpecification methodSpecification)
	{
		return methodSpecification.MethodType switch
		{
			MethodType.Void => $"ActionBehaviorBuilder{methodSpecification.GetGenericParamsString()}",
			MethodType.TaskOfT => $"FuncTaskOfBehaviorBuilder{methodSpecification.GetAsyncMethodGenericParamsString()}",
			MethodType.ValueTaskOfT => $"FuncValueTaskOfBehaviorBuilder{methodSpecification.GetAsyncMethodGenericParamsString()}",
			_ => $"FuncBehaviorBuilder{methodSpecification.GetGenericParamsString()}",
		};
	}

	private static string PrepareParameterList(MethodSpecification method)
	{
		if (method.Parameters.Count == 0)
			return "";

		var parameterDeclarations = method.Parameters
			.Select(p => $"ValueConstraint<{p.Type}>? {p.Name} = null");

		return "\n\t\t" + string.Join(",\n\t\t", parameterDeclarations);
	}
}
