using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	public static string PrepareServicesClassCode(ServicesClassSpecification spec)
	{
		// declarations of properties representing dependency instances
		var dependencyProperies = spec.Dependencies
			.Select(Functions.DependencyCode);

		// creation key-value pairs mapping dependency names to factory functions
		// that will be used to create abstract dependencies
		var abstractDependencyFactories = spec.Dependencies
			.Where(dependency => dependency.IsInterface)
			.Select(dependency =>
			$$"""
						KeyValuePair.Create<string, Func<MockedObject>>(
							"{{dependency.DependencyPropertyName}}",
							() => new {{dependency.MockedFakeTypeName}}(dependencySetup.OnlyBehaviorsWithName("{{dependency.DependencyPropertyName}}")))
			""");

		// comma separated dependency factories to pass to DependencyCollection constructor
		var strAbstractDependencyFactories = string.Join(",\n", abstractDependencyFactories);

		// TODO: when an abstract dependency is passed as a named instance - do not create a fake
		return
			$$"""
			// <auto-generated />
			#nullable enable
			using System;
			using System.Collections.Generic;
			using ZuraTDD;

			namespace {{spec.OutputNamespace}};

			/// <summary>
			/// Services used by the test cases for <see cref="{{spec.TestSubjectFullyQualifiedName}}" />.
			/// </summary>
			internal class {{spec.ServicesClassName}} : ITestSubjectDependencies
			{
				private DependencyCollection mockedDependencies;

				private readonly INamedDependencySetup[] dependencySetup;

				public {{spec.ServicesClassName}}(IEnumerable<INamedDependencySetup> dependencySetup)
				{
					this.dependencySetup = dependencySetup.ToArray();
					this.mockedDependencies = new(
			{{strAbstractDependencyFactories}});
				}

			{{string.Join("\n\n", dependencyProperies)}}

				public object this[string name] => mockedDependencies[name];
			}
			""";
	}
}

static file class Functions
{
	public static string DependencyCode(DependencySpecification dependency)
	{
		return dependency.IsInterface
			? AbstractDependencyCode(dependency)
			: SolidDependencyCode(dependency);
	}

	private static string AbstractDependencyCode(DependencySpecification dependency)
	{
		return
			$$"""
				/// <summary>
				/// Mock for the "{{dependency.DependencyPropertyName}}" parameter of the test subject constructor.
				/// Returns an instance of <see cref="{{dependency.FullyQualifiedName}}" />.
				/// </summary>
				public {{dependency.FullyQualifiedName}} {{dependency.DependencyPropertyName}}
				{
					get {
						var valueSetup = this.dependencySetup
							.OfType<NamedDependency<{{dependency.FullyQualifiedName}}>>()
							.FirstOrDefault(setup => setup.DependencyName == "{{dependency.DependencyPropertyName}}");
			
						return valueSetup != null
							? valueSetup.Instance
							: ({{dependency.FullyQualifiedName}})mockedDependencies["{{dependency.DependencyPropertyName}}"];
					}
				}
			""";
	}

	private static string SolidDependencyCode(DependencySpecification dependency)
	{
		return
			$$"""
				/// <summary>
				/// Returns an instance of <see cref="{{dependency.FullyQualifiedName}}" /> which was either provided as a TestPart
				/// or is a default value of the type.
				/// </summary>
				public {{dependency.FullyQualifiedName}} {{dependency.DependencyPropertyName}}
				{
					get {
						var valueSetup = this.dependencySetup
							.OfType<NamedDependency<{{dependency.FullyQualifiedName}}>>()
							.FirstOrDefault(setup => setup.DependencyName == "{{dependency.DependencyPropertyName}}");

						#pragma warning disable CS8603 // Possible null reference return.
						return valueSetup != null
							? valueSetup.Instance
							: default;
						#pragma warning restore CS8603 // Possible null reference return.
					}
				}
			""";
	}
}
