using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	public static string MockedTypeExpectClassesCode(MockedTypeSpecification dependency)
	{
		var methods = dependency.Methods
			.Select(method => Functions.ServiceBuilderMethodCode(dependency, method));

		var methodCode = string.Join("\n\n", methods);

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;
			
			namespace {{dependency.OutputNamespace}};

			/// <summary>
			/// An expectation setup object for <see cref="{{dependency.TypeInfo.TypeName}}" />.
			/// </summary>
			internal class {{dependency.ExpectTypeName}}
				: {{dependency.TypeInfo.TypeName}}_ExpectBuilder
			{
				public {{dependency.ExpectTypeName}}(
					MockedObject existingFake)
					: base(new ExpectedDependencyCallImmediateProcessor(existingFake))
				{
				}
			}

			internal class {{dependency.TypeInfo.TypeName}}_ExpectStaticBuilder
				: {{dependency.TypeInfo.TypeName}}_ExpectBuilder
			{
				public {{dependency.TypeInfo.TypeName}}_ExpectStaticBuilder(
					string dependencyName)
					: base(new ExpectedDependencyCallNameProcessor(dependencyName))
				{
				}
			}
			
			internal class {{dependency.TypeInfo.TypeName}}_ExpectBuilder
			{
				private IExpectedDependencyCallProcessor processor;

				protected {{dependency.TypeInfo.TypeName}}_ExpectBuilder(
					IExpectedDependencyCallProcessor processor)
				{
					this.processor = processor;
				}

			{{methodCode}}
			}
			""";
	}
}

static file class Functions
{
	public static string ServiceBuilderMethodCode(
		MockedTypeSpecification service,
		MethodSpecification method)
	{
		return
			$$"""
				/// <summary>
				/// Builds call expectations for <see cref="{{service.TypeInfo.TypeName}}.{{method.MethodName}}" />.
				/// </summary>
				public ExpectedDependencyCallBuilder {{method.MethodName}}({{PrepareParameterList(method)}})
				{
					return new(
						{{service.MockedTypeMethodsTypeName}}.{{method.Token}},
						new ValueSetConstraint([
							{{string.Join(",\n\t\t\t\t", method.Parameters.Select(p => $"{p.Name} ?? new ValueConstraint<{p.Type}>()"))}}
						]),
						this.processor);
				}
			""";
	}

	private static string PrepareParameterList(MethodSpecification method)
	{
		if (method.Parameters.Count == 0)
			return "";

		var parameterDeclarations = method.Parameters
			.Select(p => $"ValueConstraint<{p.Type}>? {p.Name} = null");

		return "\n\t\t" + string.Join(",\n\t\t", parameterDeclarations);
	}
}
