using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	public static string MockedTypeClassCode(MockedTypeSpecification mockedType)
	{
		var methods = mockedType.Methods
			.Select(m => Functions.GenerateMethodMockingCode(mockedType, m));

		var methodsCode = string.Join("\n\n", methods);

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;
			
			namespace {{mockedType.OutputNamespace}};

			/// <summary>
			/// A mock implementation of <see cref="{{mockedType.TypeInfo.FullyQualifiedTypeName}}" />.
			/// </summary>
			internal class {{mockedType.MockedFakeTypeName}}
				: MockedObject
				, {{mockedType.TypeInfo.FullyQualifiedTypeName}}
			{
				public {{mockedType.MockedFakeTypeName}}(
					params IEnumerable<BehaviorSetup> behaviors)
					: base(behaviors)
				{
				}

				public {{mockedType.ExpectTypeName}} GetExpectObject()
				{
					return new(this);
				}

			{{methodsCode}}
			}
			""";
	}
}

static file class Functions
{
	public static string GenerateMethodMockingCode(
		MockedTypeSpecification mockedType,
		MethodSpecification mockedMethod)
	{
		var @return = mockedMethod.ReturnType == "void" ? "" : "return ";
		var genericParameters = mockedMethod.GetMethodGenericTypeParametersString();
		var paramValues = mockedMethod.GetParamValuesString();
		var defaultResult = mockedMethod.GetDefaultResult().PrependNotEmpty(",\n\t\t\t");

		return
			$$"""
				/// <summary>
				/// Simulates behavior for <see cref="{{mockedType.TypeInfo.TypeName}}.{{mockedMethod.MethodName}}" />.
				/// </summary>
				public {{mockedMethod.ReturnType}} {{mockedMethod.MethodName}}{{genericParameters}}({{ParameterDeclarations(mockedMethod)}})
				{
					this.CallTracker.ReceiveCall(
						{{mockedType.MockedTypeMethodsTypeName}}.{{mockedMethod.MethodCodeName}},
						[{{paramValues}}]);

					{{@return}}base.BehaviorSetupRunner.{{InvokeMethod(mockedMethod)}}(
						{{mockedType.MockedTypeMethodsTypeName}}.{{mockedMethod.MethodCodeName}}{{paramValues.PrependNotEmpty(",\n\t\t\t")}}{{defaultResult}});
				}
			""";
	}

	private static string ParameterDeclarations(MethodSpecification method)
	{
		if (method.Parameters.Count == 0)
			return "";

		var declarations = method.Parameters
			.Select(p => $"{p.Type} {p.Name}");

		return "\n\t\t" + string.Join(",\n\t\t", declarations);
	}

	private static string InvokeMethod(MethodSpecification method)
	{
		return method.ReturnType == "void"
			? $"InvokeActionBehavior{method.GetGenericParamsString()}"
			: $"InvokeFuncBehavior{method.GetGenericParamsString()}";
	}
}
