using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	/// <summary>
	/// Generates code for the static class containing MethodInfo tokens for all public methods of the mocked object.
	/// </summary>
	public static string MockedTypeMethodsClassCode(MockedTypeSpecification dependency)
	{
		var methodsTokens = dependency.Methods
			.Select(Functions.MockedObjectMethodToken);

		var strTokens = string.Join("\n\n", methodsTokens);

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using System;
			using System.Reflection;
			using ZuraTDD;

			namespace {{dependency.OutputNamespace}};

			/// <summary>
			/// This class lists methods of <see cref="{{dependency.TypeInfo.FullyQualifiedTypeName}}" />.
			/// </summary>
			internal static class {{dependency.MockedTypeMethodsTypeName}}
			{
			{{strTokens}}
			}
			""";
	}
}

static file class Functions
{
	public static string MockedObjectMethodToken(
		MethodSpecification method)
	{
		return
			$$"""
				public static readonly MethodInfo {{method.Token}} = typeof({{method.DefiningType.FullyQualifiedTypeName}}).GetMethod(
					"{{method.MethodName}}",
					[{{ServiceMethodTokenTypeParams(method)}}])!;
			""";
	}

	private static string ServiceMethodTokenTypeParams(MethodSpecification method)
	{
		if (method.Parameters.Count == 0)
			return "";

		var parameters = method.Parameters
			.Select(p => $"typeof({p.TypeofType})");

		return string.Join(", ", parameters);
	}
}
