using System;
using System.Collections.Generic;
using System.Text;
using ZuraTDD.Generator.DataModel;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	public static string GenerateMockCode(MockObjectSpecification mockSpecification)
	{
		var mockedType = mockSpecification.MockedTypeSpecification;

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using ZuraTDD;
			
			namespace {{mockSpecification.OutputNamespace}};

			internal partial class {{mockSpecification.TypeName}}
			{
				public {{mockedType.BuilderTypeName}} Setup { get; }
				private readonly Lazy<{{mockedType.ServiceFakeTypeName}}> instance;

				public {{mockSpecification.TypeName}}()
				{
					this.Setup = new();
					instance = new(() => this.Setup.BuildInstance());
				}

				public void Deconstruct(
					out {{mockedType.BuilderTypeName}} setup,
					out Func<{{mockedType.ServiceFakeTypeName}}> buildInstance,
					out Func<{{mockedType.ExpectTypeName}}> buildExpect)
				{
					setup = Setup;
					buildInstance = () => instance.Value;
					buildExpect = () => instance.Value.GetExpectObject();
				}
			}
			""";
	}
}
