using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	public static string PrepareZuraTestClassCode(ZuraTestClassSpecification spec)
	{
		var dependencies = spec.DependenciesClass.Dependencies;

		var receives = spec.TestableMethods.Select(method => ZuraTestClassFunctions.TestSubjectReceivesCode(spec, method));
		var receivesCode = string.Join("\n\n", receives);

		var whenSnippets = spec.DependenciesClass.Dependencies.Select(ZuraTestClassFunctions.DependencyWhenCode);
		var whenCode = string.Join("\n\n", whenSnippets);

		var expectSnippets = spec.DependenciesClass.Dependencies
			.Where(dependency => dependency.IsMockable)
			.Select(ZuraTestClassFunctions.DependencyExpectCode);

		var expectCode = string.Join("\n\n", expectSnippets);

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using System;
			using System.Collections.Generic;
			using System.Threading;
			using ZuraTDD;

			namespace {{spec.OutputNamespace}};

			/// <summary>
			/// Test class for <see cref="{{spec.TestSubjectClassName}}" />.
			/// Provides Receives, When, and Expect builders.
			/// Import this class with "using static {{spec.OutputNamespace}}.{{spec.DecoratedClassName}};"
			/// in order to simplify access to "Receives", "When" and "Expect" static classes.
			/// </summary>
			public partial class {{spec.DecoratedClassName}}
			{
				/// <summary>
				/// A static class creating method calls for the tested object.
				/// </summary>
				private static class Receives
				{
			{{receivesCode}}
				}

				/// <summary>
				/// A static class creating behaviors for the tested object's dependencies.
				/// </summary>
				private static class When
				{
			{{whenCode}}
				}

				/// <summary>
				/// A static class creating expectations which must be satisfied after the tested method completes.
				/// </summary>
				private static class Expect
				{
					public static ITestResultExpectation ExceptionToBeThrown<TException>()
						where TException : Exception
					{
						return new ExpectedException<TException>();
					}

					public static ITestResultExpectation ResultMatching<TResult>(Predicate<TResult> predicate)
					{
						return new ExpectedResultMatching<TResult>(predicate);
					}

					public static ITestResultExpectation ResultEqualTo<TResult>(TResult expectedValue)
					{
						return new ExpectedResultMatching<TResult>(value => value!.Equals(expectedValue));
					}

			{{expectCode}}
				}
			}
			""";
	}
}

static file class ZuraTestClassFunctions
{
	public static string TestSubjectReceivesCode(
		ZuraTestClassSpecification spec,
		MethodSpecification method)
	{
		var parameterDeclarations = method.Parameters.Select(p => $"{ReceivesParameterType(p)} {p.Name} = default");
		var parameterList = string.Join(", ", parameterDeclarations);

		var parameterNames = method.Parameters.Select(p => p.Name);
		var parameterValues = string.Join(", ", parameterNames);

		return
			$$"""
					/// <summary>
					/// Defines a call to the <see cref="{{spec.TestSubjectFullyQualifiedClassName}}.{{method.MethodName}}"/> method.
					/// </summary>
					public static {{method.PrepareReceiveSpecificationType()}}
						{{method.MethodName}}({{parameterList}})
					{
						#pragma warning disable CS8604
						return new (
							obj => (obj as {{spec.TestSubjectClassName}})!.{{method.MethodName}}({{parameterValues}}));
						#pragma warning restore CS8604
					}
			""";
	}

	private static string ReceivesParameterType(ParameterSpecification parameter)
	{
		if(parameter.IsReferenceType)
		{
			return parameter.TypeOfOperatorTypeName + "?";
		}
		else
		{
			return parameter.TypeOfOperatorTypeName;
		}
	}

	public static string DependencyWhenCode(DependencySpecification dependency)
	{
		if (dependency.IsMockable)
		{
			var genericTypeParams = (0 < dependency.AppliedTypeParamNames.Count)
				? $"<{string.Join(", ", dependency.AppliedTypeParamNames)}>"
				: string.Empty;

			return
				$$"""
						/// <summary>
						/// A builder producing behaviors for <see cref="{{dependency.DeclaringNamespace}}.{{dependency.DependencyType.TypeName}}" />
						/// which will be passed as "{{dependency.DependencyPropertyName}}" to the test subject.
						/// </summary>
						internal static {{dependency.DependencyType.TypeName}}_NamedInstanceBuilder{{genericTypeParams}} {{dependency.DependencyPropertyName}}
							=> new {{dependency.DependencyType.TypeName}}_NamedInstanceBuilder{{genericTypeParams}}("{{dependency.DependencyPropertyName}}");
				""";
		}
		else
		{
			return
				$$"""
						/// <summary>
						/// A builder allowing to specifiy an instance of <see cref="{{dependency.DeclaringNamespace}}.{{dependency.DependencyType.TypeName}}" />
						/// which will be passed as "{{dependency.DependencyPropertyName}}" to the test subject.
						/// </summary>
						internal static {{dependency.DependencyType.TypeName}}_NamedInstanceBuilder {{dependency.DependencyPropertyName}}
							=> new {{dependency.DependencyType.TypeName}}_NamedInstanceBuilder("{{dependency.DependencyPropertyName}}");
				""";
		}
	}

	public static string DependencyExpectCode(DependencySpecification mockedDependency)
	{
		return
			$$"""
					/// <summary>
					/// A builder producing expectations for <see cref="{{mockedDependency.DeclaringNamespace}}.{{mockedDependency.DependencyType.TypeName}}" />
					/// which will be passed as "{{mockedDependency.DependencyPropertyName}}" to the test subject.
					/// </summary>
					internal static {{mockedDependency.DependencyType.TypeName}}_ExpectStaticBuilder {{mockedDependency.DependencyPropertyName}}
						=> new {{mockedDependency.DependencyType.TypeName}}_ExpectStaticBuilder("{{mockedDependency.DependencyPropertyName}}");
			""";
	}
}
