using ZuraTDD.Generator.DataModel;
using System.Linq;

namespace ZuraTDD.Generator;

internal partial class TemplateProcessor
{
	/// <summary>
	/// Generates code for the static class containing MethodInfo tokens for all public methods of the service.
	/// </summary>
	public static string ServiceMethodsClassCode(ServiceSpecification service)
	{
		var methodsTokens = service.Methods
			.Select(m => Functions.ServiceMethodToken(service, m));

		var strTokens = string.Join("\n\n", methodsTokens);

		return
			$$"""
			// <auto-generated />
			#nullable enable
			using System;
			using System.Reflection;
			using ZuraTDD;

			namespace {{service.OutputNamespace}};

			/// <summary>
			/// This class lists methods of <see cref="{{service.FullyQualifiedName}}" />.
			/// </summary>
			internal static class {{service.ServiceMethodsTypeName}}
			{
			{{strTokens}}
			}
			""";
	}
}

static file class Functions
{
	public static string ServiceMethodToken(ServiceSpecification service, MethodSpecification method)
	{
		return
			$$"""
				public static readonly MethodInfo {{method.Token}} = typeof({{service.DeclaringNamespace}}.{{service.ServiceTypeName}}).GetMethod(
					"{{method.MethodName}}",
					[{{ServiceMethodTokenTypeParams(method)}}])!;
			""";
	}

	private static string ServiceMethodTokenTypeParams(MethodSpecification method)
	{
		if (method.Parameters.Count == 0)
			return "";

		var parameters = method.Parameters
			.Select(p => $"typeof({p.TypeofType})");

		return string.Join(", ", parameters);
	}
}
